import type { Area } from "@/types/area";
import type { Cafe } from "@/types/cafe";
import type { Feature } from "@/types/feature";

export const MOCK_AREAS: Area[] = [
  {
    id: "a1",
    name: "Cihideung",
    slug: "cihideung",
    description: "Pusat kuliner dan coffee shop hits di Tasikmalaya",
    image_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
    cafe_count: 12,
  },
  {
    id: "a2",
    name: "Tamansari",
    slug: "tamansari",
    description: "Area yang tenang dengan banyak pilihan cafe aesthetic",
    image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    cafe_count: 8,
  },
  {
    id: "a3",
    name: "Pusat Kota",
    slug: "pusat-kota",
    description: "Jantung kota dengan coffee shop yang mudah dijangkau",
    image_url: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80",
    cafe_count: 10,
  },
  {
    id: "a4",
    name: "Mangkubumi",
    slug: "mangkubumi",
    description: "Area berkembang dengan banyak spot coffee shop baru",
    image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    cafe_count: 7,
  },
  {
    id: "a5",
    name: "Indihiang",
    slug: "indihiang",
    description: "Spot nongkrong asri dengan suasana semi outdoor",
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    cafe_count: 5,
  },
  {
    id: "a6",
    name: "Empangsari",
    slug: "empangsari",
    description: "Spot nongkrong asri dengan suasana semi outdoor",
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    cafe_count: 3,
  },
  {
    id: "a7",
    name: "Unsil",
    slug: "unsil",
    description: "Area kampus dengan banyak pilihan cafe aesthetic",
    image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    cafe_count: 3,
  },
  {
    id: "a8",
    name: "Cisinga",
    slug: "cisinga",
    description: "Area luar kota tasik dengan pilihan cafe dengan view indah",
    image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    cafe_count: 3,
  },
];

export const FEATURES: Feature[] = [
  {
    id: "f1",
    name: "WiFi",
    slug: "wifi",
    icon: "Wifi",
  },
  {
    id: "f2",
    name: "Power Outlet",
    slug: "power-outlet",
    icon: "Plug",
  },
  {
    id: "f3",
    name: "Work Friendly",
    slug: "work-friendly",
    icon: "Laptop",
  },
  {
    id: "f4",
    name: "Outdoor",
    slug: "outdoor",
    icon: "TreePine",
  },
  {
    id: "f5",
    name: "Smoking Area",
    slug: "smoking-area",
    icon: "Cigarette",
  },
  {
    id: "f6",
    name: "Pet Friendly",
    slug: "pet-friendly",
    icon: "PawPrint",
  },
  {
    id: "f7",
    name: "Meeting Friendly",
    slug: "meeting-friendly",
    icon: "Users",
  },
  {
    id: "f8",
    name: "Mushola",
    slug: "prayer-room",
    icon: "Moon",
  },
];

export const MOCK_CAFES: Cafe[] = [
  {
    id: "c1",
    area_id: "a6",
    name: "Toko Kopi Sukses Berkah",
    slug: "toko-kopi-sukses-berkah",
    short_description: "Cafe tanpa rokok, tanpa musik, tempat yang tenang untuk bekerja atau belajar. ",
    full_description: "Toko Kopi Sukses Berkah adalah salah satu coffee shop paling nyaman di Empangsari. Dengan konsep zero smoking Area serta atmosfer yang minim kebisingan, tempat kami ideal untuk berdiskusi, bekerja (WFC), atau menikmati waktu santai tanpa distraksi. Sebuah ruang yang berbeda untuk menikmati kopi dengan lebih nyaman. Kami menantikan kehadiran Anda.",
    address: "Jl. RAA. Wiratanuningrat, Empangsari",
    opening_hours: {
      senin: { open: "07:00", close: "22:00" },
      selasa: { open: "07:00", close: "22:00" },
      rabu: { open: "07:00", close: "22:00" },
      kamis: { open: "07:00", close: "22:00" },
      jumat: { open: "07:00", close: "22:00" },
      sabtu: { open: "07:00", close: "22:00" },
      minggu: { open: "07:00", close: "22:00" },
    },
    latitude: -7.3236837,
    longitude: 108.2235971,
    instagram_url: "https://instagram.com/kopisuksesberkah",
    maps_url: "https://maps.google.com/?cid=4901530890895579998&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAMYASAF&hl=en-US&source=embed",
    is_published: true,
    created_at: "2024-01-01T00:00:00Z",
    area: MOCK_AREAS[5],
    features: [FEATURES[0], FEATURES[1], FEATURES[2], FEATURES[7]],
    photos: [
      { id: "p1", cafe_id: "c1", image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80", sort_order: 1 },
      { id: "p2", cafe_id: "c1", image_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80", sort_order: 2 },
      { id: "p3", cafe_id: "c1", image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80", sort_order: 3 },
    ],
  },
  {
    id: "c2",
    area_id: "a6",
    name: "Notre Socielle",
    slug: "notre-socielle",
    short_description: "Cozy cafe dengan vibes modern industrial, spot foto Instagrammable dan nyaman untu WFC.",
    full_description: "Notre Socielle menawarkan pengalaman ngopi yang berbeda dengan lokasinya di rooftop. Pemandangan kota Tasikmalaya dari atas sangat memukau, apalagi saat golden hour. Cocok untuk meeting santai atau sekedar nongkrong sambil menikmati angin sore.",
    address: "Jl. Cimulu No.32, Tawangsari, Kec. Tawang, Tasikmalaya",
    opening_hours: {
      senin: { open: "09:00", close: "22:00" },
      selasa: { open: "09:00", close: "22:00" },
      rabu: { open: "09:00", close: "22:00" },
      kamis: { open: "09:00", close: "22:00" },
      jumat: { open: "09:00", close: "22:00" },
      sabtu: { open: "09:00", close: "23:00" },
      minggu: { open: "08:30", close: "23:00" },
    },
    latitude: -7.3224378,
    longitude: 108.222768,
    instagram_url: "https://www.instagram.com/notresocielle",
    maps_url: "https://maps.google.com/?q=-7.329,108.221",
    is_published: true,
    created_at: "2024-01-15T00:00:00Z",
    area: MOCK_AREAS[5],
    features: [FEATURES[0], FEATURES[1], FEATURES[2], FEATURES[3], FEATURES[7]],
    photos: [
      { id: "p4", cafe_id: "c2", image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80", sort_order: 1 },
      { id: "p5", cafe_id: "c2", image_url: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80", sort_order: 2 },
    ],
  },
  {
    id: "c3",
    area_id: "a2",
    name: "Dapur Sepi",
    slug: "dapur-sepi",
    short_description: "Hidden gem di Tamansari, tenang dan asri — surga bagi introvert yang butuh fokus.",
    full_description: "Dapur Sepi hidup sesuai namanya: tenang, sepi, tapi penuh kehangatan. Berlokasi di gang kecil Tamansari yang asri, cafe ini jadi tempat favorit untuk kerja dalam diam. Tidak ada musik keras, hanya suara alam dan aroma kopi yang menemani hari produktif Anda.",
    address: "Gang Kenanga No. 3, Tamansari, Tasikmalaya",
    opening_hours: {
      senin: { open: "08:00", close: "21:00" },
      selasa: { open: "08:00", close: "21:00" },
      rabu: { open: "08:00", close: "21:00" },
      kamis: { open: "08:00", close: "21:00" },
      jumat: { open: "08:00", close: "22:00" },
      sabtu: { open: "09:00", close: "22:00" },
      minggu: null,
    },
    latitude: -7.335,
    longitude: 108.215,
    instagram_url: "https://instagram.com/dapursepi",
    maps_url: "https://maps.google.com/?q=-7.335,108.215",
    is_published: true,
    created_at: "2024-02-01T00:00:00Z",
    area: MOCK_AREAS[1],
    features: [FEATURES[0], FEATURES[1], FEATURES[2], FEATURES[3], FEATURES[7]],
    photos: [
      { id: "p6", cafe_id: "c3", image_url: "https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=800&q=80", sort_order: 1 },
      { id: "p7", cafe_id: "c3", image_url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80", sort_order: 2 },
    ],
  },
  {
    id: "c4",
    area_id: "a3",
    name: "Balai Kopi",
    slug: "balai-kopi",
    short_description: "Tempat meeting favorit di pusat kota, lengkap dengan ruang private dan WiFi kencang.",
    full_description: "Balai Kopi dirancang untuk para profesional. Lokasinya strategis di pusat kota, menyediakan ruang meeting private berkapasitas 6-10 orang yang bisa disewa per jam. WiFi fiber optik dan power outlet di setiap meja menjadi nilai plus untuk produktivitas.",
    address: "Jl. HZ. Mustofa No. 22, Pusat Kota, Tasikmalaya",
    opening_hours: {
      senin: { open: "07:00", close: "21:00" },
      selasa: { open: "07:00", close: "21:00" },
      rabu: { open: "07:00", close: "21:00" },
      kamis: { open: "07:00", close: "21:00" },
      jumat: { open: "07:00", close: "22:00" },
      sabtu: { open: "08:00", close: "22:00" },
      minggu: { open: "09:00", close: "20:00" },
    },
    latitude: -7.322,
    longitude: 108.208,
    instagram_url: "https://instagram.com/balaikopi",
    maps_url: "https://maps.google.com/?q=-7.322,108.208",
    is_published: true,
    created_at: "2024-02-15T00:00:00Z",
    area: MOCK_AREAS[2],
    features: [FEATURES[0], FEATURES[1], FEATURES[2], FEATURES[6], FEATURES[7]],
    photos: [
      { id: "p8", cafe_id: "c4", image_url: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80", sort_order: 1 },
      { id: "p9", cafe_id: "c4", image_url: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&q=80", sort_order: 2 },
    ],
  },
  {
    id: "c5",
    area_id: "a4",
    name: "Ruang Terbuka",
    slug: "ruang-terbuka",
    short_description: "Cafe outdoor dengan taman luas, sempurna untuk nongkrong sore atau weekend bersama teman.",
    full_description: "Ruang Terbuka hadir sebagai oasis hijau di tengah padatnya Mangkubumi. Taman yang luas dengan pepohonan rindang menciptakan suasana yang nyaman untuk nongkrong santai. Tersedia area bermain anak dan live music setiap akhir pekan.",
    address: "Jl. Mangkubumi Raya No. 55, Tasikmalaya",
    opening_hours: {
      senin: { open: "10:00", close: "22:00" },
      selasa: { open: "10:00", close: "22:00" },
      rabu: { open: "10:00", close: "22:00" },
      kamis: { open: "10:00", close: "22:00" },
      jumat: { open: "10:00", close: "23:00" },
      sabtu: { open: "09:00", close: "23:00" },
      minggu: { open: "09:00", close: "22:00" },
    },
    latitude: -7.318,
    longitude: 108.225,
    instagram_url: "https://instagram.com/ruangterbuka",
    maps_url: "https://maps.google.com/?q=-7.318,108.225",
    is_published: true,
    created_at: "2024-03-01T00:00:00Z",
    area: MOCK_AREAS[3],
    features: [FEATURES[3], FEATURES[4], FEATURES[5], FEATURES[7]],
    photos: [
      { id: "p10", cafe_id: "c5", image_url: "https://images.unsplash.com/photo-1470338745628-171cf53de3a8?w=800&q=80", sort_order: 1 },
      { id: "p11", cafe_id: "c5", image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80", sort_order: 2 },
    ],
  },
  {
    id: "c6",
    area_id: "a5",
    name: "Sawah Kopi",
    slug: "sawah-kopi",
    short_description: "Nikmati kopi di tepi sawah dengan pemandangan alam khas Tasik yang menenangkan jiwa.",
    full_description: "Sawah Kopi adalah pengalaman ngopi yang benar-benar berbeda. Berlokasi di Indihiang dengan view persawahan hijau yang luas, cafe ini menawarkan ketenangan yang sulit ditemukan di tempat lain. Sungguh tempat yang tepat untuk melepas penat dan me-recharge energi.",
    address: "Jl. Indihiang Permai No. 12, Tasikmalaya",
    opening_hours: {
      senin: { open: "09:00", close: "21:00" },
      selasa: { open: "09:00", close: "21:00" },
      rabu: { open: "09:00", close: "21:00" },
      kamis: { open: "09:00", close: "21:00" },
      jumat: { open: "09:00", close: "22:00" },
      sabtu: { open: "08:00", close: "22:00" },
      minggu: { open: "08:00", close: "21:00" },
    },
    latitude: -7.312,
    longitude: 108.232,
    instagram_url: "https://instagram.com/sawahkopi",
    maps_url: "https://maps.google.com/?q=-7.312,108.232",
    is_published: true,
    created_at: "2024-03-15T00:00:00Z",
    area: MOCK_AREAS[4],
    features: [FEATURES[3], FEATURES[0], FEATURES[7]],
    photos: [
      { id: "p12", cafe_id: "c6", image_url: "https://images.unsplash.com/photo-1466721591366-2d5fba72006d?w=800&q=80", sort_order: 1 },
      { id: "p13", cafe_id: "c6", image_url: "https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800&q=80", sort_order: 2 },
    ],
  },
  {
    id: "c7",
    area_id: "a2",
    name: "Irama Kafe",
    slug: "irama-kafe",
    short_description: "Live music setiap malam Jumat & Sabtu, suasana hangat untuk kumpul bareng genk.",
    full_description: "Irama Kafe adalah surga bagi pecinta musik. Setiap Jumat dan Sabtu malam, panggung kecilnya selalu ramai dengan penampilan musisi lokal berbakat. Konsep interior yang warm dan cozy membuat pengunjung betah berlama-lama.",
    address: "Jl. Tamansari Selatan No. 30, Tasikmalaya",
    opening_hours: {
      senin: { open: "15:00", close: "23:00" },
      selasa: { open: "15:00", close: "23:00" },
      rabu: { open: "15:00", close: "23:00" },
      kamis: { open: "15:00", close: "23:00" },
      jumat: { open: "15:00", close: "00:00" },
      sabtu: { open: "14:00", close: "00:00" },
      minggu: { open: "14:00", close: "22:00" },
    },
    latitude: -7.337,
    longitude: 108.217,
    instagram_url: "https://instagram.com/iramakafe",
    maps_url: "https://maps.google.com/?q=-7.337,108.217",
    is_published: true,
    created_at: "2024-04-01T00:00:00Z",
    area: MOCK_AREAS[1],
    features: [FEATURES[5], FEATURES[6]],
    photos: [
      { id: "p14", cafe_id: "c7", image_url: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80", sort_order: 1 },
      { id: "p15", cafe_id: "c7", image_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80", sort_order: 2 },
    ],
  },
  {
    id: "c8",
    area_id: "a3",
    name: "Kopi Priangan",
    slug: "kopi-priangan",
    short_description: "Kopi lokal Tasik dengan menu traditional, harga bersahabat, dan pelayanan ramah.",
    full_description: "Kopi Priangan menampilkan kearifan lokal dalam setiap cangkir. Menu andalannya adalah kopi robusta Priangan yang ditanam di pegunungan sekitar Tasikmalaya. Dengan harga yang sangat bersahabat dan suasana warung kopi modern, tempat ini cocok untuk semua kalangan.",
    address: "Jl. RE Martadinata No. 11, Tasikmalaya",
    opening_hours: {
      senin: { open: "07:00", close: "22:00" },
      selasa: { open: "07:00", close: "22:00" },
      rabu: { open: "07:00", close: "22:00" },
      kamis: { open: "07:00", close: "22:00" },
      jumat: { open: "07:00", close: "23:00" },
      sabtu: { open: "07:00", close: "23:00" },
      minggu: { open: "08:00", close: "22:00" },
    },
    latitude: -7.324,
    longitude: 108.211,
    instagram_url: "https://instagram.com/kopipriangan",
    maps_url: "https://maps.google.com/?q=-7.324,108.211",
    is_published: true,
    created_at: "2024-04-15T00:00:00Z",
    area: MOCK_AREAS[2],
    features: [FEATURES[0], FEATURES[7]],
    photos: [
      { id: "p16", cafe_id: "c8", image_url: "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80", sort_order: 1 },
      { id: "p17", cafe_id: "c8", image_url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80", sort_order: 2 },
    ],
  },
];
